export const COINS = {
  SET_PROMOTE_COINS: "SET_PROMOTE_COINS",
  SET_MAIN_COINS: "SET_MAIN_COINS",
  SET_FAVOURITE: 'SET_FAVOURITE',
  SET_UPVOTE: 'SET_UPVOTE',
  SET_SEARCH_COINS: 'SET_SEARCH_COINS',
  SET_DISPLAY_COIN: 'SET_DISPLAY_COIN',
  SET_ALL_COINS: 'SET_ALL_COINS',
  ADD_COIN: 'ADD_COIN',
  EDIT_COIN: 'EDIT_COIN',
  DELETE_COIN: 'DELETE_COIN',
}