export const GLOBAL = {
  PROGRESS_CHANGE: "PROGRESS_CHANGE",
  SET_SHOW_SUBTYPE: 'SET_SHOW_SUBTYPE',
  SET_SHOW_TYPE: 'SET_SHOW_TYPE',
  SET_ALL_ADVERTS: 'SET_ALL_ADVERTS',
  SET_DISPLAY_ADVERTS: 'SET_DISPLAY_ADVERTS',
  CHANGE_ADVERT_DISPLAY: 'CHANGE_ADVERT_DISPLAY',
}