export const apiUrls = {
  LOGIN: '/auth/login',
  SIGNUP: '/auth/signup',
  LOGOUT: '/auth/logout',
  RESEND_VERIFY_LINK: '/email/verify/resend',
  GET_USER_INFO: '/auth/get_user_info',
  SEND_RESET_EMAIL: '/password/email',
  RESET_AUTH_PASSWORD: '/password/reset',
  UPLOAD_COIN: '/upload-coin',
  GET_ALL_COINS: '/get_all_coins',
  EDIT_COIN: '/edit_coin',
  DELETE_COIN: '/delete_coin',
  GET_COINS_FROM_API: '/get_coins_from_api',
  GET_BINANCE_IDS: '/get_binance_coinids',
  GET_PROMOTE_COINS: '/get_promote_coin',
  GET_MAIN_COINS: '/get_main_coin',
  SET_SEARCH_COINS: '/get_search_coin',
  GET_DISPLAY_COIN: '/get_display_coin',
  SET_FAVOURITE: '/set_favourite',
  SET_UPVOTE: 'set_upvote',
  GET_ALL_ADVERTS: 'get_all_adverts',
  GET_DISPLAY_ADVERTS: 'get_display_adverts',
  CHANGE_ADVERT_DISPLAY: 'change_advert_display',
  UPLOAD_ADVERT: 'upload_advert',
};
